### PR TITLE
Upgrade projects to VS2022, bump the ver number.

### PR DESCRIPTION
**Pull request by happy2discover**

### CODE REVIEW

**Comment by happy2discover** [comment]
@microsoft-github-policy-service agree

**Comment by jaccz** [comment]
Thanks! The README file has references to VS 2019 that should be adjusted to, I think.

**Comment by happy2discover** [comment]
I also updated the link of [doc/pict.md](https://github.com/Microsoft/pict/blob/main/doc/pict.md).

**Comment by jaccz** [comment]
@happy2discover , I don't think so. LGTM

**Pull request merged**
